
services:
  client:
    build:
      context: ./simple-app-client
    ports:
      - "3000:3000"
    depends_on:
      - identity
      - api
      - otel-collector
      - oteltui

  identity:
    build:
      context: ./simple-app-identity
    ports:
      - "3001:3001"
    environment:
      OTEL_EXPORTER_OTLP_ENDPOINT: https://0.0.0.0:4318

  api:
    build:
      context: ./simple-app-api
    ports:
      - "3002:3002"
    environment:
      OTEL_EXPORTER_OTLP_ENDPOINT: https://0.0.0.0:4318

  oteltui:
    image: ymtdzzz/otel-tui:latest
    container_name: otel-tui
    stdin_open: true
    tty: true
    # Override entrypoint if you want use options
    entrypoint: ["/otel-tui", "--enable-zipkin"]

  otel-collector:
      image: otel/opentelemetry-collector:latest
      volumes:
        - ./otel-collector-config.yml:/etc/otel-collector-config.yml
      command: ["--config", "/etc/otel-collector-config.yml"]
      ports:
        - "4317:4317" # OTLP gRPC receiver
        - "4318:4318" # OTLP HTTP receiver
