receivers:
  otlp:
    protocols:
      grpc:
        endpoint: 0.0.0.0:4317
      http:
        endpoint: 0.0.0.0:4318
        cors:
          allowed_origins:
            - "https://*"
            - "http://*"
          allowed_headers:
            - "*"

exporters:
  debug:

  otlp:
    endpoint: oteltui:4318
service:
  pipelines:
    traces:
      receivers: [otlp]
      exporters: [debug, otlp]
    logs:
      receivers: [otlp]
      exporters: [debug, otlp]
